network:
  version: 2
  ethernets:
    eno1:
      dhcp4: no
      addresses:
        - 192.168.100.100/24
      gateway4: 192.168.100.1
      nameservers:
        addresses: [8.8.8.8, 8.8.4.4]
    enp2s0:
      dhcp4: true
