# This is the network config written by 'subiquity'
network:
  ethernets:
    eno1:
      dhcp4: no
      addresses:
        - 192.168.178.100/24
      gateway4: 192.168.178.1
    enp2s0:
      dhcp4: true
  version: 2
